# Generated by Django 4.2.6 on 2023-11-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circular", "0002_delete_circularbusstop"),
    ]

    operations = [
        migrations.RemoveField(model_name="location", name="type",),
    ]
