# Generated by Django 4.2.6 on 2023-10-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Congestion',
        ),
    ]
