# Generated by Django 4.2.6 on 2023-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropoff', '0002_delete_congestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleCurrentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people_waiting', models.PositiveIntegerField()),
                ('is_executing', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Single Current Line',
            },
        ),
        migrations.DeleteModel(
            name='CurrentLine',
        ),
    ]
